# Generated by Django 4.1.1 on 2023-07-10 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SalonSigoApp', '0002_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signing',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalonSigoApp.procedure'),
        ),
    ]
